---
# tasks file for k8s-airgap
- name: create bundle directory
  file:
    path: "{{ lookup('env', 'HOME') }}/bundle"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0775'
    state: directory
  delegate_to: localhost

- name: check for kurl tarball first
  stat:
    path: "{{ lookup('env', 'HOME') }}/bundle/latest.tar.gz"
  register: k8star
  delegate_to: localhost

- name: fetch the installer tarball
  get_url:
    url: https://k8s.kurl.sh/bundle/latest.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/bundle/latest.tar.gz"
  delegate_to: localhost

- name: unpack the tarball to the airgap node
  unarchive:
    src: "{{ lookup('env', 'HOME') }}/bundle/latest.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/bundle/"
    creates: "{{ lookup('env', 'HOME')}}/bundle/kurl"

- name: run the install script to install k8s
  shell: cat ${HOME}/bundle/install.sh | sudo bash -s airgap
  args:
    chdir: "{{ lookup('env', 'HOME')}}/bundle"

- name: reload shell
  shell: bash -l

- name: validate k3s cluster deployment
  shell: kubectl get nodes
  vars: 
    ansible_become: false
  register: node

- name: display nodes
  debug:
    var: node.stdout_lines 

- name: list core pods
  shell: kubectl get pods -A
  vars: 
    ansible_become: false
  register: pods

- name: display pods
  debug:
    var: pods.stdout_lines

